[package]
name = "a01_addition"
version = "0.1.0"
authors = ["Aleman778 <alexander.mennborg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"